language: python
python:
  - "2.7"
  - "3.5"
#- "3.5-dev" # 3.5 development branch
#sudo: true
before_install:
  - wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
# command to install dependencies
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose pandas bokeh pep8 flake8
  - pip install python-coveralls nose-cov unittest2 flake8-pep257
  - bash -c 'if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then pip install functools32; fi'
  - "pip install $(python setup.py --require)"
# command to run tests
script:
  - nosetests --with-cov --cov icllib --cov-config .coveragerc --logging-level=INFO

after_success:
  - coveralls --config_file .coveragerc

notifications:
  slack:
    secure: phL6xPeAL5vEIuDjVfad4eM+Hc9thAzeWUKWxVVYxgaTt04hPq7z/Vfgh6kDdRThHn0f6VKnd+3aN2qSciJpxa9WoVjGN6SnOH0UPLAatLRVzv4CC4FIgn/V9M3Ko7m9Fvhg8CND/zLdW+M9W6fhZQ73H6QYDehb5n+glOPxyxY0hWXhZqG94T6pyWkvy4RdimuR/GdA/ZSnGLA+p6OZZf9wfrS58HuD9EQFtc522Lw+9w/c/5nFK3QU0YdMmhrJVENGVFLrLfBOjrPKLGV86Ne0wAjFlkA1JSh83d9XjQaT5afwQf4eD6EeIwRjMZfhaSqJpsxkxZ3TxOeKd1AH8Zbr9pvwE0f0yLlg00Qcer5NltnrAwk/Eb5k4VjREEhWLe2MXl8nof1adE8HZa1RI0/621O8/0muDnfVRiGQs3lWL1/MnAcXoqQVFYBMGjjiQPGuWgumICLbEhn2mKmktgJsWEsa2qUA26l+pNzYKModGDfrBrWiGFpvb2MtMxp3k7Hh4VOYoX5LmqESwTA4yWAYiVJZ0VAonWV2kpzDmV9emHdOMWqqTtltEu6n0jgSz3e711p/oJOB3qN8l9DY2tKRELeK+Dv0lyT6x89jtwc5VDRs/GC4LgV35zOc3+jpvGGgQ+UpemdnCDtIHl/AczK2D6x2yvgNjyOvYbVdDvI=
